'use client';
import { useEffect, useMemo, useState } from 'react';

const empty = { title:'Your Amazing Offer', desc:'Create a beautiful landing page for your ad campaign.', btn:'Watch Now 🎬', url:'', wa:'', waMessage:'', imgs:[], blocks:[], published:false, template:'ad' };
const makeId=()=>Math.random().toString(36).slice(2,10);
async function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.65));};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function migrate(data){if(data.blocks?.length)return {...empty,...data};const blocks=[];(data.imgs||[]).forEach(src=>blocks.push({id:makeId(),type:'image',src,width:100,height:360,url:''}));return {...empty,...data,blocks};}

export default function Builder(){
 const [form,setForm]=useState(empty),[pageId,setPageId]=useState(''),[saved,setSaved]=useState([]),[orders,setOrders]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[tab,setTab]=useState('builder');
 const publishedUrl=useMemo(()=>pageId&&typeof window!=='undefined'?`${window.location.origin}/p/${pageId}`:'',[pageId]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const updateBlock=(id,patch)=>setForm(f=>({...f,blocks:f.blocks.map(b=>b.id===id?{...b,...patch}:b)}));
 const addBlock=(type,extra={})=>setForm(f=>({...f,blocks:[...f.blocks,{id:makeId(),type,...extra}]}));
 const move=(i,dir)=>setForm(f=>{const a=[...f.blocks],j=i+dir;if(j<0||j>=a.length)return f;[a[i],a[j]]=[a[j],a[i]];return {...f,blocks:a}});
 const removeBlock=id=>setForm(f=>({...f,blocks:f.blocks.filter(b=>b.id!==id)}));
 const loadSaved=async()=>{try{const r=await fetch('/api/saved-pages',{cache:'no-store'}),d=await r.json();if(r.ok)setSaved(d.pages||[])}catch{setNotice('Could not load saved pages.')}};
 const loadOrders=async()=>{try{const r=await fetch('/api/orders',{cache:'no-store'}),d=await r.json();if(r.ok)setOrders(d.orders||[])}catch{setNotice('Could not load orders.')}};
 useEffect(()=>{loadSaved();loadOrders()},[]);
 const upload=async e=>{const files=Array.from(e.target.files||[]);if(!files.length)return;setNotice('Optimizing images…');try{for(const file of files.slice(0,12)){const src=await compressImage(file);addBlock('image',{src,width:100,height:360,url:''})}setNotice(`${Math.min(files.length,12)} image(s) added.`)}catch{setNotice('Could not process an image.')}e.target.value=''};
 const save=async publish=>{setBusy(true);setNotice(publish?'Publishing…':'Saving…');try{const id=pageId||makeId();const payload={...form,id,published:publish||Boolean(form.published)};const r=await fetch('/api/pages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||'Save failed');setPageId(d.id);setForm(f=>({...f,published:payload.published}));await loadSaved();setNotice(publish?'Published successfully.':'Saved permanently.')}catch(e){setNotice(e.message||'Could not save.')}finally{setBusy(false)}};
 const openSaved=async id=>{setBusy(true);try{const r=await fetch(`/api/pages/${id}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setForm(migrate(d));setPageId(id);setTab('builder');setNotice('Saved page loaded for editing.')}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const newPage=()=>{setForm(empty);setPageId('');setTab('builder');setNotice('New landing page ready.')};
 return <><header className="header"><div className="brand"><b>AdPage Builder</b><small>Build • Save • Publish</small></div><nav className="nav"><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}>Builder</button><button className={tab==='saved'?'active':''} onClick={()=>{setTab('saved');loadSaved()}}>SavePublish</button><button className={tab==='orders'?'active':''} onClick={()=>{setTab('orders');loadOrders()}}>Orders <em>{orders.length}</em></button></nav><div className="top-actions"><button className="secondary" onClick={()=>save(false)} disabled={busy}>Save</button><button onClick={()=>save(true)} disabled={busy}>{busy?'Working…':'Publish'}</button></div></header>
 <main className="wrap"><div className="hero"><div><span className="eyebrow">AD LANDING PAGE BUILDER</span><h1>{form.template==='ecommerce'?'E-commerce Web Landing Page':'Create, save and publish.'}</h1><p>Build your page block by block, save it permanently, and share the published URL.</p></div><div className="hero-actions"><button className="new-btn" onClick={newPage}>＋ New Page</button></div></div>
 {tab==='builder'&&<div className="builder-layout"><aside className="card block-panel"><div className="section-title"><div><h2>Add Blocks</h2><p className="muted">Build in any order you want.</p></div></div><div className="template-box"><b>Start from template</b><button onClick={()=>{setForm({...empty,template:'ecommerce',title:'Amazing Product',desc:'Order your product today.',blocks:[{id:makeId(),type:'text',text:'🔥 Special Offer Today',align:'center'},{id:makeId(),type:'image',src:'',width:100,height:360,url:''},{id:makeId(),type:'text',text:'Premium quality. Fast delivery.',align:'center'},{id:makeId(),type:'order',heading:'Order Now',button:'Place Order',fields:true}]});setPageId('')}}>🛒 E-commerce Web Landing Page</button></div><button className="add-block" onClick={()=>addBlock('text',{text:'Write your text here…',align:'left'})}>＋ Text</button><label className="add-block file-add">＋ Image<input type="file" accept="image/*" multiple onChange={upload}/></label><button className="add-block" onClick={()=>addBlock('button',{text:'Watch Now 🎬',url:'',animation:'fade-up'})}>＋ Button</button><button className="add-block" onClick={()=>addBlock('whatsapp',{number:'',message:'',text:'WhatsApp',animation:'fade-up'})}>＋ WhatsApp</button><button className="add-block order-add" onClick={()=>addBlock('order',{heading:'Order Now',button:'Place Order',fields:true})}>＋ Order Form</button><div className="tip">💡 Add blocks repeatedly. Text → image → button → WhatsApp → image → order form — anything you want.</div></aside>
 <section className="card canvas-card"><div className="section-title"><div><h2>Landing Page</h2><p className="muted">Arrange your blocks in any order.</p></div>{pageId&&<span className="saved-pill">● Saved</span>}</div><div className="canvas">{form.blocks.length?form.blocks.map((b,i)=><BlockEditor key={b.id} block={b} index={i} total={form.blocks.length} update={p=>updateBlock(b.id,p)} move={d=>move(i,d)} remove={()=>removeBlock(b.id)}/>):<div className="canvas-empty">Choose a block from the left to start building.</div>}</div>{notice&&<div className="notice">{notice}</div>}{publishedUrl&&<div className="result"><b>{form.published?'Published URL':'Saved URL'}</b><a href={publishedUrl} target="_blank" rel="noreferrer">{publishedUrl}</a><button onClick={()=>navigator.clipboard?.writeText(publishedUrl)}>Copy URL</button></div>}</section>
 <section className="card preview"><div className="section-title"><div><h2>Live Preview</h2><p className="muted">Visitor view</p></div></div><div className="phone"><Visitor data={form} pageId={pageId}/></div></section></div>}
 {tab==='saved'&&<SavedPages saved={saved} openSaved={openSaved} loadSaved={loadSaved} />}
 {tab==='orders'&&<Orders orders={orders} loadOrders={loadOrders}/>} </main></>;
}

function BlockEditor({block,index,total,update,move,remove}){return <div className={`edit-block ${block.type}`}><div className="block-head"><b>{index+1}. {block.type==='order'?'Order Form':block.type[0].toUpperCase()+block.type.slice(1)}</b><div><button onClick={()=>move(-1)} disabled={index===0}>↑</button><button onClick={()=>move(1)} disabled={index===total-1}>↓</button><button onClick={remove}>×</button></div></div>{block.type==='text'&&<><textarea className="field" rows="3" value={block.text||''} onChange={e=>update({text:e.target.value})}/><select className="field compact" value={block.align||'left'} onChange={e=>update({align:e.target.value})}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></>}{block.type==='image'&&<><div className="image-edit">{block.src?<img src={block.src} alt=""/>:<div className="image-placeholder">Add an image</div>}<div><label>Width {block.width||100}%<input type="range" min="20" max="100" value={block.width||100} onChange={e=>update({width:Number(e.target.value)})}/></label><label>Height {block.height||360}px<input type="range" min="100" max="800" value={block.height||360} onChange={e=>update({height:Number(e.target.value)})}/></label><input className="field compact" placeholder="Image click URL (https://...)" value={block.url||''} onChange={e=>update({url:e.target.value})}/></div></div></>}{block.type==='button'&&<><input className="field compact" placeholder="Button text" value={block.text||''} onChange={e=>update({text:e.target.value})}/><input className="field compact" placeholder="https://your-link.com" value={block.url||''} onChange={e=>update({url:e.target.value})}/><select className="field compact" value={block.animation||'fade-up'} onChange={e=>update({animation:e.target.value})}><option value="none">No animation</option><option value="fade-up">Fade Up</option><option value="fade">Fade</option><option value="zoom">Zoom</option><option value="slide">Slide</option></select></>}{block.type==='whatsapp'&&<><input className="field compact" placeholder="WhatsApp number e.g. 8801..." value={block.number||''} onChange={e=>update({number:e.target.value})}/><input className="field compact" placeholder="Message (optional)" value={block.message||''} onChange={e=>update({message:e.target.value})}/><input className="field compact" placeholder="Button text" value={block.text||'WhatsApp'} onChange={e=>update({text:e.target.value})}/></>}{block.type==='order'&&<><input className="field compact" placeholder="Order form heading" value={block.heading||''} onChange={e=>update({heading:e.target.value})}/><input className="field compact" placeholder="Submit button text" value={block.button||''} onChange={e=>update({button:e.target.value})}/><p className="muted">The published page will collect Name, Phone, Address and Quantity.</p></>}</div>}

function Visitor({data,pageId}){return <div className="visitor"><div className="ad"><span>ADVERTISEMENT</span><small>Ad space</small></div>{(data.blocks||[]).map(b=><RenderBlock key={b.id} b={b} pageId={pageId}/>)}{!data.blocks?.length&&<article className="visitor-empty"><h1>{data.title}</h1><p>{data.desc}</p></article>}</div>}
function RenderBlock({b,pageId}){if(b.type==='text')return <div className="v-text" style={{textAlign:b.align||'left'}}>{b.text}</div>;if(b.type==='image'){if(!b.src)return <div className="v-placeholder">Image block — add an image</div>;const img=<img src={b.src} alt="" style={{width:`${b.width||100}%`,height:`${b.height||360}px`}}/>;return b.url?<a href={b.url} target="_blank" rel="noreferrer" className="image-link">{img}</a>:img}if(b.type==='button')return <a className={`cta anim-${b.animation||'fade-up'}`} href={b.url||'#'} target="_blank" rel="noreferrer">{b.text||'Watch Now 🎬'}</a>;if(b.type==='whatsapp'){const n=(b.number||'').replace(/\D/g,'');return n?<a className="cta whatsapp" href={`https://wa.me/${n}${b.message?`?text=${encodeURIComponent(b.message)}`:''}`} target="_blank" rel="noreferrer">{b.text||'WhatsApp'}</a>:<div className="v-placeholder">Add WhatsApp number</div>}if(b.type==='order')return <OrderForm block={b} pageId={pageId}/>;return null}
function OrderForm({block,pageId}){const [form,setForm]=useState({name:'',phone:'',address:'',quantity:1}),[state,setState]=useState('');const submit=async e=>{e.preventDefault();if(!pageId){setState('Publish the page first to receive orders.');return}setState('Sending…');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,pageId})}),d=await r.json();if(!r.ok)throw Error(d.error);setState('Order received successfully!')}catch(e){setState(e.message||'Could not send order')}};return <form className="order-form" onSubmit={submit}><h3>{block.heading||'Order Now'}</h3><input required placeholder="Your Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Phone Number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea required placeholder="Delivery Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input type="number" min="1" placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><button type="submit">{block.button||'Place Order'}</button>{state&&<small>{state}</small>}</form>}
function SavedPages({saved,openSaved,loadSaved}){return <div className="card full-card"><div className="section-title"><div><h2>SavePublish Page</h2><p className="muted">All your saved landing pages.</p></div><button className="link-btn" onClick={loadSaved}>Refresh</button></div>{saved.length?saved.map(p=><div className="saved-item" key={p.id}><div><b>{p.title||'Untitled page'}</b><small>{p.template==='ecommerce'?'E-commerce Web Landing Page • ':''}{p.published?'Published':'Saved'} • {p.updatedAt?new Date(p.updatedAt).toLocaleString():''}</small></div><div><button onClick={()=>openSaved(p.id)}>Edit</button><a href={`/p/${p.id}`} target="_blank" rel="noreferrer">Open</a></div></div>):<div className="empty">No saved pages yet.</div>}</div>}
function Orders({orders,loadOrders}){return <div className="card full-card"><div className="section-title"><div><h2>Orders Dashboard</h2><p className="muted">Orders submitted from published landing pages.</p></div><button className="link-btn" onClick={loadOrders}>Refresh</button></div>{orders.length?<div className="orders-table">{orders.map(o=><div className="order-row" key={o.id}><div><b>{o.name}</b><small>{o.phone} • Qty: {o.quantity}</small><span>{o.address}</span></div><div><strong>{o.status||'New'}</strong><small>{o.createdAt?new Date(o.createdAt).toLocaleString():''}</small></div></div>)}</div>:<div className="empty">No orders yet. Add an Order Form block and publish your page.</div>}</div>}
